services:
  zyfra:
    image: zyfra_intern
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn intern_project.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
    depends_on:
      - zyfra

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  staticfiles:
  media:
