# Generated by Django 5.2.4 on 2025-07-19 21:32

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('date_purchase', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=10)),
                ('operation_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='vehicle/frontend/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicletype'),
        ),
    ]
