# Generated by Django 5.2.4 on 2025-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='operation_status',
            field=models.CharField(choices=[('В работе', 'In Use'), ('Простой', 'Idle'), ('Ремонт', 'Repair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
