# Generated by Django 5.2.4 on 2025-07-20 12:24

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
