# Generated by Django 5.2.4 on 2025-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicleimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='operation_status',
            field=models.CharField(choices=[('in_use', 'В работе'), ('idle', 'Простой'), ('repair', 'Ремонт')], max_length=50),
        ),
    ]
