# Generated by Django 5.2.4 on 2025-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_alter_attribute_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='status',
            field=models.CharField(choices=[('Установлено', 'Installed'), ('На складе', 'In Stock'), ('В ремонте', 'Repair'), ('Ожидает ремонт', 'Awaiting Repair')], max_length=50),
        ),
    ]
